title: Lit Reviews
description: Noting down literature reviews for reference!
theme: just-the-docs

url: https://kalpitthakkar.github.io/paper-reviews

compress_html:
  blanklines: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
